#pragma once

#include <stddef.h>
#include <stdint.h>
#include "core/str.h"
#include "core/sealed.h"
#include "base/location.h"

SEALED_KIND(token,
    // PUNCTUATION
    TOKEN_SEMICOLON, TOKEN_COMMA, TOKEN_COLON,
    // DEF
    TOKEN_CONST, TOKEN_VAR, TOKEN_FUN, TOKEN_SET,
    // FUN
    TOKEN_RETURN,
    // CONDITIONS
    TOKEN_IF, TOKEN_ELIF, TOKEN_ELSE,
    // BRACES
	TOKEN_OPENING_FIGURE_BRACE, TOKEN_CLOSING_FIGURE_BRACE,
	TOKEN_OPENING_CIRCLE_BRACE, TOKEN_CLOSING_CIRCLE_BRACE,
    // OPERATIONS
	TOKEN_EQUALS, TOKEN_NOT_EQUALS, TOKEN_GE, TOKEN_LE, TOKEN_GREATER, TOKEN_LESS,
    TOKEN_DIVIDE, TOKEN_MULTIPLY, TOKEN_MINUS, TOKEN_PLUS, TOKEN_MOD,
    // INTERHITED
    TOKEN_IDENT,
    TOKEN_UINT, TOKEN_STR
);

SEALED_BASE(token,
    (location_t, location)
);

SEALED_CHILD_DEFINE(token, TOKEN_IDENT, ident,
    (str_t, ident)
);

SEALED_CHILD_DEFINE_FREE(token, TOKEN_UINT, uint,
    (uint64_t, value)
);

SEALED_CHILD_DEFINE_FREE(token, TOKEN_STR, str,
    (str_t, value)
);

SEALED_FREE_DEFINE(token);

ARR_TYPED_ALIAS_DEFINE(tokens, token_t);