#pragma once

#define _VAARGS_LEN(_32, _31, _30, _29, _28, _27, _26, _25, _24, _23, _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8, _7, _6, _5, _4, _3, _2, _1, N, ...) N
#define VAARGS_LEN(...) _VAARGS_LEN(__VA_ARGS__ __VA_OPT__(,) 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)

#define FOREACH0(MAP, MAP_LAST)
#define FOREACH1(MAP, MAP_LAST, first_arg) MAP_LAST(first_arg) FOREACH0(MAP, MAP_LAST)
#define FOREACH2(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH1(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH3(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH2(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH4(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH3(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH5(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH4(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH6(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH5(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH7(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH6(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH8(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH7(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH9(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH8(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH10(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH9(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH11(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH10(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH12(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH11(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH13(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH12(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH14(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH13(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH15(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH14(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH16(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH15(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH17(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH16(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH18(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH17(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH19(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH18(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH20(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH19(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH21(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH20(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH22(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH21(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH23(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH22(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH24(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH23(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH25(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH24(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH26(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH25(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH27(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH26(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH28(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH27(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH29(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH28(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH30(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH29(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH31(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH30(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH32(MAP, MAP_LAST, first_arg, ...) MAP(first_arg) FOREACH31(MAP, MAP_LAST, ##__VA_ARGS__)

#define _FOREACHN(N, MAP, MAP_LAST, ...) FOREACH##N(MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACHN(N, MAP, MAP_LAST, ...) _FOREACHN(N, MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH_WITH_LAST(MAP, MAP_LAST, ...) FOREACHN(VAARGS_LEN(__VA_ARGS__), MAP, MAP_LAST, ##__VA_ARGS__)
#define FOREACH(MAP, ...) FOREACHN(VAARGS_LEN(__VA_ARGS__), MAP, MAP, ##__VA_ARGS__)